const ALPHABETIC_INDEX = [
  "A Comme Amour - Clyaderman",
  "A Love Dream - Liszt",
  "Air on the G String - Bach",
  "Arioso - Bach",
  "Au Clair de la lune",
  "Auld Lang Syne",
  "Ave Maria - Bach-Gounod",
  "Ave Maria - Schubert",
  "Bridal March - Wagner",
  "Clair de Lune - Debussy",
  "Consolation No 3 - Liszt",
  "Cradle Song - Hauser",
  "CS Theme and Variations PRIMO - Compton",
  "CS Theme and Variations SECONDO - Compton",
  "Edelweiss - Rodgers and Hammerstein",
  "Etude Op 10 No 3 - Chopin",
  "Fantaisie-Impromptu - Chopin",
  "Fur Elise - Beethoven",
  "God Save the King",
  "Happy Birthday",
  "Home Sweet Home - Bishop",
  "Humoreske - Dvorak",
  "I Can\'t Help Falling In Love With You",
  "Impromptu in G flat major - Schubert",
  "In a Monastery Garden - Ketelbey",
  "Intermezzo - Mascagni",
  "Jesu, Joy of Man\'s Desiring - JS Bach",
  "Joyous Farmer - Schumann",
  "La Paloma - Yradier",
  "La Vie En Rose",
  "Largo - Handel",
  "Londonderry Air",
  "Long, Long Ago",
  "Love Story",
  "Meditation - Massenet",
  "Melody in F - Rubinstein",
  "Minuet - Boccherini",
  "Minuet - Mozart",
  "Minuet In G - Beethoven",
  "Moonlight Sonata 1st Movement - Beethoven",
  "Moonlight Sonata 2nd Movement - Beethoven",
  "Moonlight Sonata 3rd Movement - Beethoven",
  "Musette - JS Bach",
  "My Old Kentucky Home",
  "My Tribute - Crouch",
  "Nocturne Op 9 No 2 - Chopin",
  "O Divine Redeemer - Gounod",
  "O Sole Mio - Eduardo di Capua",
  "Old Black Joe",
  "Passacaglia - Handel Halvorsen",
  "Pathetique Sonata 1st Movement - Beethoven",
  "Pathetique Sonata 2nd Movement - Beethoven",
  "Pathetique Sonata 3rd Movement - Beethoven",
  "Plaisir d\'amour - Martini",
  "Prelude in C-sharp Minor - Rachmaninoff",
  "Prelude Op. 28, No. 7 - Chopin",
  "Prelude Op. 28, No. 20 - Chopin",
  "Reverie - Debussy",
  "River Flows In You - Yiruma",
  "Salut D\'Amour - Elgar",
  "Serenade - Liszt",
  "Serenade - Schubert",
  "Serenata - Toselli",
  "Silent Night, Holy Night - Gruber",
  "Spring Song - Mendelssohn",
  "Surprise Symphony - Haydn",
  "Swanee River",
  "The Beautiful Blue Danube - Strauss",
  "The Entertainer - Joplin",
  "The Holy City - Adams",
  "The Lord\'s Prayer - Malotte",
  "The Moon Represents My Heart - Teng",
  "The Prayer - Sager and Foster",
  "The Star Spangled Banner",
  "The Swan - Saint-Saens",
  "The Unfinished Symphony - Schubert",
  "Traumerei - Schumann",
  "Two Arabesques I - Debussy",
  "Waltz in A Flat - Brahms",
  "Waltz in C Sharp Minor - Chopin",
  "Wedding March - Mendelssohn",
  "You\'ll Never Walk Alone - Rodgers and Hammerstein"
];  // end ALPHABETIC_INDEX

const ALPHABETIC_PAGES = [
  "about",
  "A Comme Amour - Clyaderman",
  "A Comme Amour - Clyaderman2",
  "A Comme Amour - Clyaderman3",
  "A Comme Amour - Clyaderman4",
  "A Love Dream - Liszt",
  "A Love Dream - Liszt2",
  "A Love Dream - Liszt3",
  "A Love Dream - Liszt4",
  "A Love Dream - Liszt5",
  "A Love Dream - Liszt6",
  "A Love Dream - Liszt7",
  "A Love Dream - Liszt8",
  "Air on the G String - Bach",
  "Air on the G String - Bach2",
  "Air on the G String - Bach3",
  "Air on the G String - Bach4",
  "Arioso - Bach",
  "Au Clair de la lune",
  "Auld Lang Syne",
  "Ave Maria - Bach-Gounod",
  "Ave Maria - Bach-Gounod2",
  "Ave Maria - Bach-Gounod3",
  "Ave Maria - Schubert",
  "Ave Maria - Schubert2",
  "Bridal March - Wagner",
  "Bridal March - Wagner2",
  "Clair de Lune - Debussy",
  "Clair de Lune - Debussy2",
  "Clair de Lune - Debussy3",
  "Clair de Lune - Debussy4",
  "Clair de Lune - Debussy5",
  "Clair de Lune - Debussy6",
  "Consolation No 3 - Liszt",
  "Consolation No 3 - Liszt2",
  "Consolation No 3 - Liszt3",
  "Consolation No 3 - Liszt4",
  "Cradle Song - Hauser",
  "CS Theme and Variations PRIMO - Compton",
  "CS Theme and Variations PRIMO - Compton2",
  "CS Theme and Variations PRIMO - Compton3",
  "CS Theme and Variations PRIMO - Compton4",
  "CS Theme and Variations PRIMO - Compton5",
  "CS Theme and Variations PRIMO - Compton6",
  "CS Theme and Variations PRIMO - Compton7",
  "CS Theme and Variations PRIMO - Compton8",
  "CS Theme and Variations PRIMO - Compton9",
  "CS Theme and Variations SECONDO - Compton",
  "CS Theme and Variations SECONDO - Compton2",
  "CS Theme and Variations SECONDO - Compton3",
  "CS Theme and Variations SECONDO - Compton4",
  "CS Theme and Variations SECONDO - Compton5",
  "CS Theme and Variations SECONDO - Compton6",
  "CS Theme and Variations SECONDO - Compton7",
  "CS Theme and Variations SECONDO - Compton8",
  "CS Theme and Variations SECONDO - Compton9",
  "Edelweiss - Rodgers and Hammerstein",
  "Edelweiss - Rodgers and Hammerstein2",
  "Etude Op 10 No 3 - Chopin",
  "Etude Op 10 No 3 - Chopin2",
  "Etude Op 10 No 3 - Chopin3",
  "Etude Op 10 No 3 - Chopin4",
  "Etude Op 10 No 3 - Chopin5",
  "Etude Op 10 No 3 - Chopin6",
  "Etude Op 10 No 3 - Chopin7",
  "Fantaisie-Impromptu - Chopin",
  "Fantaisie-Impromptu - Chopin2",
  "Fantaisie-Impromptu - Chopin3",
  "Fantaisie-Impromptu - Chopin4",
  "Fantaisie-Impromptu - Chopin5",
  "Fantaisie-Impromptu - Chopin6",
  "Fantaisie-Impromptu - Chopin7",
  "Fantaisie-Impromptu - Chopin8",
  "Fantaisie-Impromptu - Chopin9",
  "Fantaisie-Impromptu - Chopin10",
  "Fantaisie-Impromptu - Chopin11",
  "Fantaisie-Impromptu - Chopin12",
  "Fantaisie-Impromptu - Chopin13",
  "Fantaisie-Impromptu - Chopin14",
  "Fur Elise - Beethoven",
  "Fur Elise - Beethoven2",
  "Fur Elise - Beethoven3",
  "Fur Elise - Beethoven4",
  "God Save the King",
  "Happy Birthday",
  "Happy Birthday2",
  "Happy Birthday3",
  "Happy Birthday4",
  "Home Sweet Home - Bishop",
  "Humoreske - Dvorak",
  "Humoreske - Dvorak2",
  "Humoreske - Dvorak3",
  "I Can\'t Help Falling In Love With You",
  "I Can\'t Help Falling In Love With You2",
  "Impromptu in G flat major - Schubert",
  "Impromptu in G flat major - Schubert2",
  "Impromptu in G flat major - Schubert3",
  "Impromptu in G flat major - Schubert4",
  "Impromptu in G flat major - Schubert5",
  "Impromptu in G flat major - Schubert6",
  "Impromptu in G flat major - Schubert7",
  "Impromptu in G flat major - Schubert8",
  "Impromptu in G flat major - Schubert9",
  "In a Monastery Garden - Ketelbey",
  "In a Monastery Garden - Ketelbey2",
  "In a Monastery Garden - Ketelbey3",
  "In a Monastery Garden - Ketelbey4",
  "In a Monastery Garden - Ketelbey5",
  "In a Monastery Garden - Ketelbey6",
  "Intermezzo - Mascagni",
  "Intermezzo - Mascagni2",
  "Intermezzo - Mascagni3",
  "Jesu, Joy of Man\'s Desiring - JS Bach",
  "Jesu, Joy of Man\'s Desiring - JS Bach2",
  "Jesu, Joy of Man\'s Desiring - JS Bach3",
  "Jesu, Joy of Man\'s Desiring - JS Bach4",
  "Jesu, Joy of Man\'s Desiring - JS Bach5",
  "Joyous Farmer - Schumann",
  "La Paloma - Yradier",
  "La Paloma - Yradier2",
  "La Vie En Rose",
  "La Vie En Rose2",
  "Largo - Handel",
  "Largo - Handel2",
  "Londonderry Air",
  "Londonderry Air2",
  "Long, Long Ago",
  "Love Story",
  "Love Story2",
  "Love Story3",
  "Meditation - Massenet",
  "Meditation - Massenet2",
  "Meditation - Massenet3",
  "Meditation - Massenet4",
  "Melody in F - Rubinstein",
  "Melody in F - Rubinstein2",
  "Minuet - Boccherini",
  "Minuet - Boccherini2",
  "Minuet - Mozart",
  "Minuet In G - Beethoven",
  "Minuet In G - Beethoven2",
  "Moonlight Sonata 1st Movement - Beethoven",
  "Moonlight Sonata 1st Movement - Beethoven2",
  "Moonlight Sonata 1st Movement - Beethoven3",
  "Moonlight Sonata 1st Movement - Beethoven4",
  "Moonlight Sonata 2nd Movement - Beethoven",
  "Moonlight Sonata 2nd Movement - Beethoven2",
  "Moonlight Sonata 3rd Movement - Beethoven",
  "Moonlight Sonata 3rd Movement - Beethoven2",
  "Moonlight Sonata 3rd Movement - Beethoven3",
  "Moonlight Sonata 3rd Movement - Beethoven4",
  "Moonlight Sonata 3rd Movement - Beethoven5",
  "Moonlight Sonata 3rd Movement - Beethoven6",
  "Moonlight Sonata 3rd Movement - Beethoven7",
  "Moonlight Sonata 3rd Movement - Beethoven8",
  "Moonlight Sonata 3rd Movement - Beethoven9",
  "Moonlight Sonata 3rd Movement - Beethoven10",
  "Moonlight Sonata 3rd Movement - Beethoven11",
  "Moonlight Sonata 3rd Movement - Beethoven12",
  "Moonlight Sonata 3rd Movement - Beethoven13",
  "Moonlight Sonata 3rd Movement - Beethoven14",
  "Moonlight Sonata 3rd Movement - Beethoven15",
  "Moonlight Sonata 3rd Movement - Beethoven16",
  "Moonlight Sonata 3rd Movement - Beethoven17",
  "Moonlight Sonata 3rd Movement - Beethoven18",
  "Moonlight Sonata 3rd Movement - Beethoven19",
  "Moonlight Sonata 3rd Movement - Beethoven20",
  "Musette - JS Bach",
  "My Old Kentucky Home",
  "My Tribute - Crouch",
  "My Tribute - Crouch2",
  "My Tribute - Crouch3",
  "My Tribute - Crouch4",
  "My Tribute - Crouch5",
  "My Tribute - Crouch6",
  "My Tribute - Crouch7",
  "My Tribute - Crouch8",
  "My Tribute - Crouch9",
  "Nocturne Op 9 No 2 - Chopin",
  "Nocturne Op 9 No 2 - Chopin2",
  "Nocturne Op 9 No 2 - Chopin3",
  "O Divine Redeemer - Gounod",
  "O Divine Redeemer - Gounod2",
  "O Divine Redeemer - Gounod3",
  "O Divine Redeemer - Gounod4",
  "O Divine Redeemer - Gounod5",
  "O Sole Mio - Eduardo di Capua",
  "O Sole Mio - Eduardo di Capua2",
  "O Sole Mio - Eduardo di Capua3",
  "Old Black Joe",
  "Passacaglia - Handel Halvorsen",
  "Passacaglia - Handel Halvorsen2",
  "Passacaglia - Handel Halvorsen3",
  "Pathetique Sonata 1st Movement - Beethoven",
  "Pathetique Sonata 1st Movement - Beethoven2",
  "Pathetique Sonata 1st Movement - Beethoven3",
  "Pathetique Sonata 1st Movement - Beethoven4",
  "Pathetique Sonata 1st Movement - Beethoven5",
  "Pathetique Sonata 1st Movement - Beethoven6",
  "Pathetique Sonata 1st Movement - Beethoven7",
  "Pathetique Sonata 1st Movement - Beethoven8",
  "Pathetique Sonata 1st Movement - Beethoven9",
  "Pathetique Sonata 1st Movement - Beethoven10",
  "Pathetique Sonata 1st Movement - Beethoven11",
  "Pathetique Sonata 1st Movement - Beethoven12",
  "Pathetique Sonata 1st Movement - Beethoven13",
  "Pathetique Sonata 2nd Movement - Beethoven",
  "Pathetique Sonata 2nd Movement - Beethoven2",
  "Pathetique Sonata 2nd Movement - Beethoven3",
  "Pathetique Sonata 2nd Movement - Beethoven4",
  "Pathetique Sonata 3rd Movement - Beethoven",
  "Pathetique Sonata 3rd Movement - Beethoven2",
  "Pathetique Sonata 3rd Movement - Beethoven3",
  "Pathetique Sonata 3rd Movement - Beethoven4",
  "Pathetique Sonata 3rd Movement - Beethoven5",
  "Pathetique Sonata 3rd Movement - Beethoven6",
  "Pathetique Sonata 3rd Movement - Beethoven7",
  "Pathetique Sonata 3rd Movement - Beethoven8",
  "Pathetique Sonata 3rd Movement - Beethoven9",
  "Plaisir d\'amour - Martini",
  "Plaisir d\'amour - Martini2",
  "Plaisir d\'amour - Martini3",
  "Plaisir d\'amour - Martini4",
  "Prelude in C-sharp Minor - Rachmaninoff",
  "Prelude in C-sharp Minor - Rachmaninoff2",
  "Prelude in C-sharp Minor - Rachmaninoff3",
  "Prelude in C-sharp Minor - Rachmaninoff4",
  "Prelude in C-sharp Minor - Rachmaninoff5",
  "Prelude in C-sharp Minor - Rachmaninoff6",
  "Prelude Op. 28, No. 7 - Chopin",
  "Prelude Op. 28, No. 20 - Chopin",
  "Reverie - Debussy",
  "Reverie - Debussy2",
  "Reverie - Debussy3",
  "Reverie - Debussy4",
  "Reverie - Debussy5",
  "River Flows In You - Yiruma",
  "River Flows In You - Yiruma2",
  "River Flows In You - Yiruma3",
  "Salut D\'Amour - Elgar",
  "Salut D\'Amour - Elgar2",
  "Salut D\'Amour - Elgar3",
  "Salut D\'Amour - Elgar4",
  "Salut D\'Amour - Elgar5",
  "Serenade - Liszt",
  "Serenade - Liszt2",
  "Serenade - Liszt3",
  "Serenade - Liszt4",
  "Serenade - Liszt5",
  "Serenade - Liszt6",
  "Serenade - Schubert",
  "Serenade - Schubert2",
  "Serenade - Schubert3",
  "Serenade - Schubert4",
  "Serenata - Toselli",
  "Serenata - Toselli2",
  "Serenata - Toselli3",
  "Silent Night, Holy Night - Gruber",
  "Spring Song - Mendelssohn",
  "Spring Song - Mendelssohn2",
  "Spring Song - Mendelssohn3",
  "Surprise Symphony - Haydn",
  "Swanee River",
  "The Beautiful Blue Danube - Strauss",
  "The Beautiful Blue Danube - Strauss2",
  "The Beautiful Blue Danube - Strauss3",
  "The Beautiful Blue Danube - Strauss4",
  "The Beautiful Blue Danube - Strauss5",
  "The Beautiful Blue Danube - Strauss6",
  "The Beautiful Blue Danube - Strauss7",
  "The Beautiful Blue Danube - Strauss8",
  "The Beautiful Blue Danube - Strauss9",
  "The Entertainer - Joplin",
  "The Entertainer - Joplin2",
  "The Entertainer - Joplin3",
  "The Entertainer - Joplin4",
  "The Holy City - Adams",
  "The Holy City - Adams2",
  "The Holy City - Adams3",
  "The Holy City - Adams4",
  "The Holy City - Adams5",
  "The Holy City - Adams6",
  "The Holy City - Adams7",
  "The Lord\'s Prayer - Malotte",
  "The Lord\'s Prayer - Malotte2",
  "The Lord\'s Prayer - Malotte3",
  "The Lord\'s Prayer - Malotte4",
  "The Moon Represents My Heart - Teng",
  "The Moon Represents My Heart - Teng2",
  "The Prayer - Sager and Foster",
  "The Prayer - Sager and Foster2",
  "The Prayer - Sager and Foster3",
  "The Prayer - Sager and Foster4",
  "The Prayer - Sager and Foster5",
  "The Prayer - Sager and Foster6",
  "The Prayer - Sager and Foster7",
  "The Star Spangled Banner",
  "The Swan - Saint-Saens",
  "The Swan - Saint-Saens2",
  "The Unfinished Symphony - Schubert",
  "Traumerei - Schumann",
  "Two Arabesques I - Debussy",
  "Two Arabesques I - Debussy2",
  "Two Arabesques I - Debussy3",
  "Two Arabesques I - Debussy4",
  "Two Arabesques I - Debussy5",
  "Two Arabesques I - Debussy6",
  "Two Arabesques I - Debussy7",
  "Waltz in A Flat - Brahms",
  "Waltz in A Flat - Brahms2",
  "Waltz in C Sharp Minor - Chopin",
  "Waltz in C Sharp Minor - Chopin2",
  "Waltz in C Sharp Minor - Chopin3",
  "Waltz in C Sharp Minor - Chopin4",
  "Waltz in C Sharp Minor - Chopin5",
  "Waltz in C Sharp Minor - Chopin6",
  "Waltz in C Sharp Minor - Chopin7",
  "Waltz in C Sharp Minor - Chopin8",
  "Wedding March - Mendelssohn",
  "Wedding March - Mendelssohn2",
  "Wedding March - Mendelssohn3",
  "Wedding March - Mendelssohn4",
  "Wedding March - Mendelssohn5",
  "Wedding March - Mendelssohn6",
  "You\'ll Never Walk Alone - Rodgers and Hammerstein",
  "You\'ll Never Walk Alone - Rodgers and Hammerstein2",
  "You\'ll Never Walk Alone - Rodgers and Hammerstein3"
];  // end ALPHABETIC_PAGES

/*
const NUMERIC_INDEX = [
  "Au Clair de la lune",
  "Auld Lang Syne",
  "Cradle Song - Hauser",
  "Edelweiss - Rodgers and Hammerstein",
  "God Save the King",
  "La Vie En Rose",
  "Long, Long Ago",
  "Melody in F - Rubinstein",
  "Minuet - Mozart",
  "Minuet In G - Beethoven",
  "Musette - JS Bach",
  "My Old Kentucky Home",
  "Old Black Joe",
  "Prelude Op. 28, No. 7 - Chopin",
  "Prelude Op. 28, No. 20 - Chopin",
  "Silent Night, Holy Night - Gruber",
  "Surprise Symphony - Haydn",
  "Swanee River",
  "The Star Spangled Banner",
  "The Unfinished Symphony - Schubert",
  "Air on the G String - Bach",
  "Arioso - Bach",
  "Ave Maria - Schubert",
  "Fur Elise - Beethoven",
  "Happy Birthday",
  "Home Sweet Home - Bishop",
  "I Can\'t Help Falling In Love With You",
  "In a Monastery Garden - Ketelbey",
  "Joyous Farmer - Schumann",
  "La Paloma - Yradier",
  "Largo - Handel",
  "Londonderry Air",
  "Love Story",
  "Meditation - Massenet",
  "O Sole Mio - Eduardo di Capua",
  "Passacaglia - Handel Halvorsen",
  "Plaisir d\'amour - Martini",
  "Reverie - Debussy",
  "River Flows In You - Yiruma",
  "Serenade - Schubert",
  "Serenata - Toselli",
  "Spring Song - Mendelssohn",
  "The Beautiful Blue Danube - Strauss",
  "The Entertainer - Joplin",
  "The Holy City - Adams",
  "The Lord\'s Prayer - Malotte",
  "The Moon Represents My Heart - Teng",
  "The Prayer - Sager and Foster",
  "The Swan - Saint-Saens",
  "Traumerei - Schumann",
  "Waltz in A Flat - Brahms",
  "You\'ll Never Walk Alone - Rodgers and Hammerstein",
  "A Love Dream - Liszt",
  "Ave Maria - Bach-Gounod",
  "Bridal March - Wagner",
  "CS Theme and Variations PRIMO - Compton",
  "CS Theme and Variations SECONDO - Compton",
  "Clair de Lune - Debussy",
  "Consolation No 3 - Liszt",
  "Etude Op 10 No 3 - Chopin",
  "Fantaisie-Impromptu - Chopin",
  "Humoreske - Dvorak",
  "Impromptu in G flat major - Schubert",
  "Intermezzo - Mascagni",
  "Jesu, Joy of Man\'s Desiring - JS Bach",
  "Minuet - Boccherini",
  "Moonlight Sonata 1st Movement - Beethoven",
  "Moonlight Sonata 2nd Movement - Beethoven",
  "Moonlight Sonata 3rd Movement - Beethoven",
  "My Tribute - Crouch",
  "Nocturne Op 9 No 2 - Chopin",
  "O Divine Redeemer - Gounod",
  "Pathetique Sonata 1st Movement - Beethoven",
  "Pathetique Sonata 2nd Movement - Beethoven",
  "Pathetique Sonata 3rd Movement - Beethoven",
  "Prelude in C-sharp Minor - Rachmaninoff",
  "Salut D\'Amour - Elgar",
  "Serenade - Liszt",
  "Two Arabesques I - Debussy",
  "Waltz in C Sharp Minor - Chopin",
  "Wedding March - Mendelssohn"
];  // end NUMERIC_INDEX
  
const NUMERIC_PAGES = [
  "about",
  "about2",
  "about3",
  "Au Clair de la lune",
  "Auld Lang Syne",
  "Cradle Song - Hauser",
  "Edelweiss - Rodgers and Hammerstein",
  "Edelweiss - Rodgers and Hammerstein2",
  "God Save the King",
  "La Vie En Rose",
  "La Vie En Rose2",
  "Long, Long Ago",
  "Melody in F - Rubinstein",
  "Melody in F - Rubinstein2",
  "Minuet - Mozart",
  "Minuet In G - Beethoven",
  "Minuet In G - Beethoven2",
  "Musette - JS Bach",
  "My Old Kentucky Home",
  "Old Black Joe",
  "Prelude Op. 28, No. 7 - Chopin",
  "Prelude Op. 28, No. 20 - Chopin",
  "Silent Night, Holy Night - Gruber",
  "Surprise Symphony - Haydn",
  "Swanee River",
  "The Star Spangled Banner",
  "The Unfinished Symphony - Schubert",
  "Air on the G String - Bach",
  "Air on the G String - Bach2",
  "Air on the G String - Bach3",
  "Air on the G String - Bach4",
  "Arioso - Bach",
  "Ave Maria - Schubert",
  "Ave Maria - Schubert2",
  "Fur Elise - Beethoven",
  "Fur Elise - Beethoven2",
  "Fur Elise - Beethoven3",
  "Fur Elise - Beethoven4",
  "Happy Birthday",
  "Happy Birthday2",
  "Happy Birthday3",
  "Happy Birthday4",
  "Home Sweet Home - Bishop",
  "I Can\'t Help Falling In Love With You",
  "I Can\'t Help Falling In Love With You2",
  "In a Monastery Garden - Ketelbey",
  "In a Monastery Garden - Ketelbey2",
  "In a Monastery Garden - Ketelbey3",
  "In a Monastery Garden - Ketelbey4",
  "In a Monastery Garden - Ketelbey5",
  "In a Monastery Garden - Ketelbey6",
  "Joyous Farmer - Schumann",
  "La Paloma - Yradier",
  "La Paloma - Yradier2",
  "Largo - Handel",
  "Largo - Handel2",
  "Londonderry Air",
  "Londonderry Air2",
  "Love Story",
  "Love Story2",
  "Love Story3",
  "Meditation - Massenet",
  "Meditation - Massenet2",
  "Meditation - Massenet3",
  "Meditation - Massenet4",
  "O Sole Mio - Eduardo di Capua",
  "O Sole Mio - Eduardo di Capua2",
  "O Sole Mio - Eduardo di Capua3",
  "Passacaglia - Handel Halvorsen",
  "Passacaglia - Handel Halvorsen2",
  "Passacaglia - Handel Halvorsen3",
  "Plaisir d\'amour - Martini",
  "Plaisir d\'amour - Martini2",
  "Plaisir d\'amour - Martini3",
  "Plaisir d\'amour - Martini4",
  "Reverie - Debussy",
  "Reverie - Debussy2",
  "Reverie - Debussy3",
  "Reverie - Debussy4",
  "Reverie - Debussy5",
  "River Flows In You - Yiruma",
  "River Flows In You - Yiruma2",
  "River Flows In You - Yiruma3",
  "Serenade - Schubert",
  "Serenade - Schubert2",
  "Serenade - Schubert3",
  "Serenade - Schubert4",
  "Serenata - Toselli",
  "Serenata - Toselli2",
  "Serenata - Toselli3",
  "Spring Song - Mendelssohn",
  "Spring Song - Mendelssohn2",
  "Spring Song - Mendelssohn3",
  "The Beautiful Blue Danube - Strauss",
  "The Beautiful Blue Danube - Strauss2",
  "The Beautiful Blue Danube - Strauss3",
  "The Beautiful Blue Danube - Strauss4",
  "The Beautiful Blue Danube - Strauss5",
  "The Beautiful Blue Danube - Strauss6",
  "The Beautiful Blue Danube - Strauss7",
  "The Beautiful Blue Danube - Strauss8",
  "The Beautiful Blue Danube - Strauss9",
  "The Entertainer - Joplin",
  "The Entertainer - Joplin2",
  "The Entertainer - Joplin3",
  "The Entertainer - Joplin4",
  "The Holy City - Adams",
  "The Holy City - Adams2",
  "The Holy City - Adams3",
  "The Holy City - Adams4",
  "The Holy City - Adams5",
  "The Holy City - Adams6",
  "The Holy City - Adams7",
  "The Lord\'s Prayer - Malotte",
  "The Lord\'s Prayer - Malotte2",
  "The Lord\'s Prayer - Malotte3",
  "The Lord\'s Prayer - Malotte4",
  "The Moon Represents My Heart - Teng",
  "The Moon Represents My Heart - Teng2",
  "The Prayer - Sager and Foster",
  "The Prayer - Sager and Foster2",
  "The Prayer - Sager and Foster3",
  "The Prayer - Sager and Foster4",
  "The Prayer - Sager and Foster5",
  "The Prayer - Sager and Foster6",
  "The Prayer - Sager and Foster7",
  "The Swan - Saint-Saens",
  "The Swan - Saint-Saens2",
  "Traumerei - Schumann",
  "Waltz in A Flat - Brahms",
  "Waltz in A Flat - Brahms2",
  "You\'ll Never Walk Alone - Rodgers and Hammerstein",
  "You\'ll Never Walk Alone - Rodgers and Hammerstein2",
  "You\'ll Never Walk Alone - Rodgers and Hammerstein3",
  "A Love Dream - Liszt",
  "A Love Dream - Liszt2",
  "A Love Dream - Liszt3",
  "A Love Dream - Liszt4",
  "A Love Dream - Liszt5",
  "A Love Dream - Liszt6",
  "A Love Dream - Liszt7",
  "A Love Dream - Liszt8",
  "Ave Maria - Bach-Gounod",
  "Ave Maria - Bach-Gounod2",
  "Ave Maria - Bach-Gounod3",
  "Bridal March - Wagner",
  "Bridal March - Wagner2",
  "CS Theme and Variations PRIMO - Compton",
  "CS Theme and Variations PRIMO - Compton2",
  "CS Theme and Variations PRIMO - Compton3",
  "CS Theme and Variations PRIMO - Compton4",
  "CS Theme and Variations PRIMO - Compton5",
  "CS Theme and Variations PRIMO - Compton6",
  "CS Theme and Variations PRIMO - Compton7",
  "CS Theme and Variations PRIMO - Compton8",
  "CS Theme and Variations PRIMO - Compton9",
  "CS Theme and Variations SECONDO - Compton",
  "CS Theme and Variations SECONDO - Compton2",
  "CS Theme and Variations SECONDO - Compton3",
  "CS Theme and Variations SECONDO - Compton4",
  "CS Theme and Variations SECONDO - Compton5",
  "CS Theme and Variations SECONDO - Compton6",
  "CS Theme and Variations SECONDO - Compton7",
  "CS Theme and Variations SECONDO - Compton8",
  "CS Theme and Variations SECONDO - Compton9",
  "Clair de Lune - Debussy",
  "Clair de Lune - Debussy2",
  "Clair de Lune - Debussy3",
  "Clair de Lune - Debussy4",
  "Clair de Lune - Debussy5",
  "Clair de Lune - Debussy6",
  "Consolation No 3 - Liszt",
  "Consolation No 3 - Liszt2",
  "Consolation No 3 - Liszt3",
  "Consolation No 3 - Liszt4",
  "Etude Op 10 No 3 - Chopin",
  "Etude Op 10 No 3 - Chopin2",
  "Etude Op 10 No 3 - Chopin3",
  "Etude Op 10 No 3 - Chopin4",
  "Etude Op 10 No 3 - Chopin5",
  "Etude Op 10 No 3 - Chopin6",
  "Etude Op 10 No 3 - Chopin7",
  "Fantaisie-Impromptu - Chopin",
  "Fantaisie-Impromptu - Chopin2",
  "Fantaisie-Impromptu - Chopin3",
  "Fantaisie-Impromptu - Chopin4",
  "Fantaisie-Impromptu - Chopin5",
  "Fantaisie-Impromptu - Chopin6",
  "Fantaisie-Impromptu - Chopin7",
  "Fantaisie-Impromptu - Chopin8",
  "Fantaisie-Impromptu - Chopin9",
  "Fantaisie-Impromptu - Chopin10",
  "Fantaisie-Impromptu - Chopin11",
  "Fantaisie-Impromptu - Chopin12",
  "Fantaisie-Impromptu - Chopin13",
  "Fantaisie-Impromptu - Chopin14",
  "Humoreske - Dvorak",
  "Humoreske - Dvorak2",
  "Humoreske - Dvorak3",
  "Impromptu in G flat major - Schubert",
  "Impromptu in G flat major - Schubert2",
  "Impromptu in G flat major - Schubert3",
  "Impromptu in G flat major - Schubert4",
  "Impromptu in G flat major - Schubert5",
  "Impromptu in G flat major - Schubert6",
  "Impromptu in G flat major - Schubert7",
  "Impromptu in G flat major - Schubert8",
  "Impromptu in G flat major - Schubert9",
  "Intermezzo - Mascagni",
  "Intermezzo - Mascagni2",
  "Intermezzo - Mascagni3",
  "Jesu, Joy of Man\'s Desiring - JS Bach",
  "Jesu, Joy of Man\'s Desiring - JS Bach2",
  "Jesu, Joy of Man\'s Desiring - JS Bach3",
  "Jesu, Joy of Man\'s Desiring - JS Bach4",
  "Jesu, Joy of Man\'s Desiring - JS Bach5",
  "Minuet - Boccherini",
  "Minuet - Boccherini2",
  "Moonlight Sonata 1st Movement - Beethoven",
  "Moonlight Sonata 1st Movement - Beethoven2",
  "Moonlight Sonata 1st Movement - Beethoven3",
  "Moonlight Sonata 1st Movement - Beethoven4",
  "Moonlight Sonata 2nd Movement - Beethoven",
  "Moonlight Sonata 2nd Movement - Beethoven2",
  "Moonlight Sonata 3rd Movement - Beethoven",
  "Moonlight Sonata 3rd Movement - Beethoven2",
  "Moonlight Sonata 3rd Movement - Beethoven3",
  "Moonlight Sonata 3rd Movement - Beethoven4",
  "Moonlight Sonata 3rd Movement - Beethoven5",
  "Moonlight Sonata 3rd Movement - Beethoven6",
  "Moonlight Sonata 3rd Movement - Beethoven7",
  "Moonlight Sonata 3rd Movement - Beethoven8",
  "Moonlight Sonata 3rd Movement - Beethoven9",
  "Moonlight Sonata 3rd Movement - Beethoven10",
  "Moonlight Sonata 3rd Movement - Beethoven11",
  "Moonlight Sonata 3rd Movement - Beethoven12",
  "Moonlight Sonata 3rd Movement - Beethoven13",
  "Moonlight Sonata 3rd Movement - Beethoven14",
  "Moonlight Sonata 3rd Movement - Beethoven15",
  "Moonlight Sonata 3rd Movement - Beethoven16",
  "Moonlight Sonata 3rd Movement - Beethoven17",
  "Moonlight Sonata 3rd Movement - Beethoven18",
  "Moonlight Sonata 3rd Movement - Beethoven19",
  "Moonlight Sonata 3rd Movement - Beethoven20",
  "My Tribute - Crouch",
  "My Tribute - Crouch2",
  "My Tribute - Crouch3",
  "My Tribute - Crouch4",
  "My Tribute - Crouch5",
  "My Tribute - Crouch6",
  "My Tribute - Crouch7",
  "My Tribute - Crouch8",
  "My Tribute - Crouch9",
  "Nocturne Op 9 No 2 - Chopin",
  "Nocturne Op 9 No 2 - Chopin2",
  "Nocturne Op 9 No 2 - Chopin3",
  "O Divine Redeemer - Gounod",
  "O Divine Redeemer - Gounod2",
  "O Divine Redeemer - Gounod3",
  "O Divine Redeemer - Gounod4",
  "O Divine Redeemer - Gounod5",
  "Pathetique Sonata 1st Movement - Beethoven",
  "Pathetique Sonata 1st Movement - Beethoven2",
  "Pathetique Sonata 1st Movement - Beethoven3",
  "Pathetique Sonata 1st Movement - Beethoven4",
  "Pathetique Sonata 1st Movement - Beethoven5",
  "Pathetique Sonata 1st Movement - Beethoven6",
  "Pathetique Sonata 1st Movement - Beethoven7",
  "Pathetique Sonata 1st Movement - Beethoven8",
  "Pathetique Sonata 1st Movement - Beethoven9",
  "Pathetique Sonata 1st Movement - Beethoven10",
  "Pathetique Sonata 1st Movement - Beethoven11",
  "Pathetique Sonata 1st Movement - Beethoven12",
  "Pathetique Sonata 1st Movement - Beethoven13",
  "Pathetique Sonata 2nd Movement - Beethoven",
  "Pathetique Sonata 2nd Movement - Beethoven2",
  "Pathetique Sonata 2nd Movement - Beethoven3",
  "Pathetique Sonata 2nd Movement - Beethoven4",
  "Pathetique Sonata 3rd Movement - Beethoven",
  "Pathetique Sonata 3rd Movement - Beethoven2",
  "Pathetique Sonata 3rd Movement - Beethoven3",
  "Pathetique Sonata 3rd Movement - Beethoven4",
  "Pathetique Sonata 3rd Movement - Beethoven5",
  "Pathetique Sonata 3rd Movement - Beethoven6",
  "Pathetique Sonata 3rd Movement - Beethoven7",
  "Pathetique Sonata 3rd Movement - Beethoven8",
  "Pathetique Sonata 3rd Movement - Beethoven9",
  "Prelude in C-sharp Minor - Rachmaninoff",
  "Prelude in C-sharp Minor - Rachmaninoff2",
  "Prelude in C-sharp Minor - Rachmaninoff3",
  "Prelude in C-sharp Minor - Rachmaninoff4",
  "Prelude in C-sharp Minor - Rachmaninoff5",
  "Prelude in C-sharp Minor - Rachmaninoff6",
  "Salut D\'Amour - Elgar",
  "Salut D\'Amour - Elgar2",
  "Salut D\'Amour - Elgar3",
  "Salut D\'Amour - Elgar4",
  "Salut D\'Amour - Elgar5",
  "Serenade - Liszt",
  "Serenade - Liszt2",
  "Serenade - Liszt3",
  "Serenade - Liszt4",
  "Serenade - Liszt5",
  "Serenade - Liszt6",
  "Two Arabesques I - Debussy",
  "Two Arabesques I - Debussy2",
  "Two Arabesques I - Debussy3",
  "Two Arabesques I - Debussy4",
  "Two Arabesques I - Debussy5",
  "Two Arabesques I - Debussy6",
  "Two Arabesques I - Debussy7",
  "Waltz in C Sharp Minor - Chopin",
  "Waltz in C Sharp Minor - Chopin2",
  "Waltz in C Sharp Minor - Chopin3",
  "Waltz in C Sharp Minor - Chopin4",
  "Waltz in C Sharp Minor - Chopin5",
  "Waltz in C Sharp Minor - Chopin6",
  "Waltz in C Sharp Minor - Chopin7",
  "Waltz in C Sharp Minor - Chopin8",
  "Wedding March - Mendelssohn",
  "Wedding March - Mendelssohn2",
  "Wedding March - Mendelssohn3",
  "Wedding March - Mendelssohn4",
  "Wedding March - Mendelssohn5",
  "Wedding March - Mendelssohn6"
];  // end NUMERIC_PAGES
*/


/////////////////////////////////////////////////////////////////////
// HELP_PAGES
const HELP_PAGES = [
  "help",
  "help2",
  "help3",
  "help4"
];
// end HELP_PAGES
